# Generated by Django 5.2.17 on 2026-08-13 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Menu')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='Caminho/URL')),
                ('icone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícone (Lucide)')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pai', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenus', to='core.menu', verbose_name='Menu Pai')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
                'ordering': ['ordem', 'nome'],
            },
        ),
    ]
