# Generated by Django 5.2.17 on 2026-08-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='menus', to='auth.group', verbose_name='Grupos com Acesso'),
        ),
    ]
