# Generated by Django 5.2.17 on 2026-08-13 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menu_grupos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecursoHumano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_nascimento', models.DateField(blank=True, null=True, verbose_name='Data de Nascimento')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], default='M', max_length=1, verbose_name='Sexo')),
                ('rg', models.CharField(blank=True, max_length=20, null=True, verbose_name='RG')),
                ('data_emissao_rg', models.DateField(blank=True, null=True, verbose_name='Data de Emissão RG')),
                ('orgao_expedidor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Órgão Expedidor')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('titulo_eleitor', models.CharField(blank=True, max_length=20, null=True, verbose_name='Título de Eleitor')),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('escolaridade', models.CharField(blank=True, max_length=50, null=True, verbose_name='Escolaridade')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('tipo_logradouro', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tipo de Logradouro')),
                ('logradouro', models.CharField(blank=True, max_length=150, null=True, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('municipio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Município')),
                ('unidade_socioassistencial', models.BooleanField(default=False, verbose_name='Unidade Socioassistencial?')),
                ('orgao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Órgão')),
                ('responsavel_orgao', models.BooleanField(default=False, verbose_name='Responsável pelo Órgão?')),
                ('tipo_servidor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Servidor')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('funcao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Função')),
                ('num_conselho_classe', models.CharField(blank=True, max_length=30, null=True, verbose_name='Nº Conselho Classe')),
                ('data_inicio_trabalho', models.DateField(blank=True, null=True, verbose_name='Data de Início do Trabalho')),
                ('data_fim_trabalho', models.DateField(blank=True, null=True, verbose_name='Data de Fim do Trabalho')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recurso_humano', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recurso Humano',
                'verbose_name_plural': 'Recursos Humanos',
            },
        ),
    ]
