# Generated by Django 5.2.17 on 2026-08-13 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recursohumano'),
    ]

    operations = [
        migrations.AddField(
            model_name='recursohumano',
            name='uf',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='UF'),
        ),
    ]
