# Generated by Django 5.2.17 on 2026-08-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_recursohumano_uf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cbo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='Código')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'CBO',
                'verbose_name_plural': 'CBOs',
                'db_table': 'classificacao_brasileira_de_ocupacao',
            },
        ),
        migrations.CreateModel(
            name='Cid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('codigo_cid', models.CharField(max_length=20, verbose_name='Código CID')),
            ],
            options={
                'verbose_name': 'CID',
                'verbose_name_plural': 'CIDs',
                'db_table': 'cid',
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ibge', models.IntegerField(unique=True, verbose_name='Código IBGE')),
                ('sigla', models.CharField(max_length=2, unique=True, verbose_name='Sigla')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
                'db_table': 'estado',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_uf', models.IntegerField(verbose_name='Código UF')),
                ('codigo_ibge', models.CharField(max_length=20, verbose_name='Código IBGE')),
                ('municipio', models.CharField(max_length=255, verbose_name='Município')),
            ],
            options={
                'verbose_name': 'Município',
                'verbose_name_plural': 'Municípios',
                'db_table': 'municipio',
            },
        ),
    ]
