# Generated by Django 5.2.17 on 2026-08-14 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_cbo_cid_estado_municipio'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaixaEtaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'FaixaEtaria',
                'verbose_name_plural': 'FaixaEtarias',
                'db_table': 'faixa_etaria',
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'db_table': 'feriado',
            },
        ),
        migrations.CreateModel(
            name='OrientacaoSexual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'OrientacaoSexual',
                'verbose_name_plural': 'OrientacaoSexuals',
                'db_table': 'orientacao_sexual',
            },
        ),
        migrations.CreateModel(
            name='Potencialidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Potencialidades',
                'verbose_name_plural': 'Potencialidadess',
                'db_table': 'potencialidades',
            },
        ),
        migrations.CreateModel(
            name='Raca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Raca',
                'verbose_name_plural': 'Racas',
                'db_table': 'raca',
            },
        ),
        migrations.CreateModel(
            name='Religioes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'Religioes',
                'verbose_name_plural': 'Religioess',
                'db_table': 'religioes',
            },
        ),
        migrations.CreateModel(
            name='TipoAbastecimentoAgua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoAbastecimentoAgua',
                'verbose_name_plural': 'TipoAbastecimentoAguas',
                'db_table': 'tipo_abastecimento_agua',
            },
        ),
        migrations.CreateModel(
            name='TipoAcessibilidadeDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoAcessibilidadeDomicilio',
                'verbose_name_plural': 'TipoAcessibilidadeDomicilios',
                'db_table': 'tipo_acessibilidade_domicilio',
            },
        ),
        migrations.CreateModel(
            name='TipoAreaSegmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoAreaSegmento',
                'verbose_name_plural': 'TipoAreaSegmentos',
                'db_table': 'tipo_area_segmento',
            },
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoAtividade',
                'verbose_name_plural': 'TipoAtividades',
                'db_table': 'tipo_atividade',
            },
        ),
        migrations.CreateModel(
            name='TipoAtividadeGrupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoAtividadeGrupos',
                'verbose_name_plural': 'TipoAtividadeGruposs',
                'db_table': 'tipo_atividade_grupos',
            },
        ),
        migrations.CreateModel(
            name='TipoBeneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoBeneficio',
                'verbose_name_plural': 'TipoBeneficios',
                'db_table': 'tipo_beneficio',
            },
        ),
        migrations.CreateModel(
            name='TipoColetaLixo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoColetaLixo',
                'verbose_name_plural': 'TipoColetaLixos',
                'db_table': 'tipo_coleta_lixo',
            },
        ),
        migrations.CreateModel(
            name='TipoConstrucaoDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoConstrucaoDomicilio',
                'verbose_name_plural': 'TipoConstrucaoDomicilios',
                'db_table': 'tipo_construcao_domicilio',
            },
        ),
        migrations.CreateModel(
            name='TipoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoCurso',
                'verbose_name_plural': 'TipoCursos',
                'db_table': 'tipo_curso',
            },
        ),
        migrations.CreateModel(
            name='TipoDeficiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoDeficiencia',
                'verbose_name_plural': 'TipoDeficiencias',
                'db_table': 'tipo_deficiencia',
            },
        ),
        migrations.CreateModel(
            name='TipoEncaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoEncaminhamento',
                'verbose_name_plural': 'TipoEncaminhamentos',
                'db_table': 'tipo_encaminhamento',
            },
        ),
        migrations.CreateModel(
            name='TipoEscoamentoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoEscoamentoSanitario',
                'verbose_name_plural': 'TipoEscoamentoSanitarios',
                'db_table': 'tipo_escoamento_sanitario',
            },
        ),
        migrations.CreateModel(
            name='TipoEscolaridade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoEscolaridade',
                'verbose_name_plural': 'TipoEscolaridades',
                'db_table': 'tipo_escolaridade',
            },
        ),
        migrations.CreateModel(
            name='TipoEspecieDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoEspecieDomicilio',
                'verbose_name_plural': 'TipoEspecieDomicilios',
                'db_table': 'tipo_especie_domicilio',
            },
        ),
        migrations.CreateModel(
            name='TipoEstadoCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoEstadoCivil',
                'verbose_name_plural': 'TipoEstadoCivils',
                'db_table': 'tipo_estado_civil',
            },
        ),
        migrations.CreateModel(
            name='TipoFuncao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoFuncao',
                'verbose_name_plural': 'TipoFuncaos',
                'db_table': 'tipo_funcao',
            },
        ),
        migrations.CreateModel(
            name='TipoGruposTradicionaisEspecificos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoGruposTradicionaisEspecificos',
                'verbose_name_plural': 'TipoGruposTradicionaisEspecificoss',
                'db_table': 'tipo_grupos_tradicionais_especificos',
            },
        ),
        migrations.CreateModel(
            name='TipoIluminacaoDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoIluminacaoDomicilio',
                'verbose_name_plural': 'TipoIluminacaoDomicilios',
                'db_table': 'tipo_iluminacao_domicilio',
            },
        ),
        migrations.CreateModel(
            name='TipoLocaisRealizacoesServicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoLocaisRealizacoesServicos',
                'verbose_name_plural': 'TipoLocaisRealizacoesServicoss',
                'db_table': 'tipo_locais_realizacoes_servicos',
            },
        ),
        migrations.CreateModel(
            name='TipoLocalNascimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoLocalNascimento',
                'verbose_name_plural': 'TipoLocalNascimentos',
                'db_table': 'tipo_local_nascimento',
            },
        ),
        migrations.CreateModel(
            name='TipoMedidaSocioeducativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoMedidaSocioeducativa',
                'verbose_name_plural': 'TipoMedidaSocioeducativas',
                'db_table': 'tipo_medida_socioeducativa',
            },
        ),
        migrations.CreateModel(
            name='TipoNecessitaCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoNecessitaCuidado',
                'verbose_name_plural': 'TipoNecessitaCuidados',
                'db_table': 'tipo_necessita_cuidado',
            },
        ),
        migrations.CreateModel(
            name='TipoOrgaoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoOrgaoRecurso',
                'verbose_name_plural': 'TipoOrgaoRecursos',
                'db_table': 'tipo_orgao_recurso',
            },
        ),
        migrations.CreateModel(
            name='TipoOrigemCadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoOrigemCadastro',
                'verbose_name_plural': 'TipoOrigemCadastros',
                'db_table': 'tipo_origem_cadastro',
            },
        ),
        migrations.CreateModel(
            name='TipoParentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoParentesco',
                'verbose_name_plural': 'TipoParentescos',
                'db_table': 'tipo_parentesco',
            },
        ),
        migrations.CreateModel(
            name='TipoPisoDomicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoPisoDomicilio',
                'verbose_name_plural': 'TipoPisoDomicilios',
                'db_table': 'tipo_piso_domicilio',
            },
        ),
        migrations.CreateModel(
            name='TipoProfissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoProfissao',
                'verbose_name_plural': 'TipoProfissaos',
                'db_table': 'tipo_profissao',
            },
        ),
        migrations.CreateModel(
            name='TipoQualificacaoProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoQualificacaoProfissional',
                'verbose_name_plural': 'TipoQualificacaoProfissionals',
                'db_table': 'tipo_qualificacao_profissional',
            },
        ),
        migrations.CreateModel(
            name='TipoRegistroCivil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoRegistroCivil',
                'verbose_name_plural': 'TipoRegistroCivils',
                'db_table': 'tipo_registro_civil',
            },
        ),
        migrations.CreateModel(
            name='TipoResidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoResidencia',
                'verbose_name_plural': 'TipoResidencias',
                'db_table': 'tipo_residencia',
            },
        ),
        migrations.CreateModel(
            name='TiposAnimais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TiposAnimais',
                'verbose_name_plural': 'TiposAnimaiss',
                'db_table': 'tipos_animais',
            },
        ),
        migrations.CreateModel(
            name='TiposAtendimentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TiposAtendimentos',
                'verbose_name_plural': 'TiposAtendimentoss',
                'db_table': 'tipos_atendimentos',
            },
        ),
        migrations.CreateModel(
            name='TiposContatosParentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TiposContatosParentes',
                'verbose_name_plural': 'TiposContatosParentess',
                'db_table': 'tipos_contatos_parentes',
            },
        ),
        migrations.CreateModel(
            name='TiposEfeitosDescumprimentosCondicionalidades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TiposEfeitosDescumprimentosCondicionalidades',
                'verbose_name_plural': 'TiposEfeitosDescumprimentosCondicionalidadess',
                'db_table': 'tipos_efeitos_descumprimentos_condicionalidades',
            },
        ),
        migrations.CreateModel(
            name='TipoSerieCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoSerieCurso',
                'verbose_name_plural': 'TipoSerieCursos',
                'db_table': 'tipo_serie_curso',
            },
        ),
        migrations.CreateModel(
            name='TipoServicoProgramaProjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoServicoProgramaProjeto',
                'verbose_name_plural': 'TipoServicoProgramaProjetos',
                'db_table': 'tipo_servico_programa_projeto',
            },
        ),
        migrations.CreateModel(
            name='TipoServicoProtecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoServicoProtecao',
                'verbose_name_plural': 'TipoServicoProtecaos',
                'db_table': 'tipo_servico_protecao',
            },
        ),
        migrations.CreateModel(
            name='TipoServidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoServidor',
                'verbose_name_plural': 'TipoServidors',
                'db_table': 'tipo_servidor',
            },
        ),
        migrations.CreateModel(
            name='TipoSituacaoViolenciaEViolacaoDireitos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoSituacaoViolenciaEViolacaoDireitos',
                'verbose_name_plural': 'TipoSituacaoViolenciaEViolacaoDireitoss',
                'db_table': 'tipo_situacao_violencia_e_violacao_direitos',
            },
        ),
        migrations.CreateModel(
            name='TiposOrgaos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TiposOrgaos',
                'verbose_name_plural': 'TiposOrgaoss',
                'db_table': 'tipos_orgaos',
            },
        ),
        migrations.CreateModel(
            name='TiposPeriodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TiposPeriodos',
                'verbose_name_plural': 'TiposPeriodoss',
                'db_table': 'tipos_periodos',
            },
        ),
        migrations.CreateModel(
            name='TiposRecursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TiposRecursos',
                'verbose_name_plural': 'TiposRecursoss',
                'db_table': 'tipos_recursos',
            },
        ),
        migrations.CreateModel(
            name='TiposRelacoesConvivenciasFamiliares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TiposRelacoesConvivenciasFamiliares',
                'verbose_name_plural': 'TiposRelacoesConvivenciasFamiliaress',
                'db_table': 'tipos_relacoes_convivencias_familiares',
            },
        ),
        migrations.CreateModel(
            name='TiposServicosSociais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TiposServicosSociais',
                'verbose_name_plural': 'TiposServicosSociaiss',
                'db_table': 'tipos_servicos_sociais',
            },
        ),
        migrations.CreateModel(
            name='TiposTemposResidenciasCidadesPopulacoesRuas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TiposTemposResidenciasCidadesPopulacoesRuas',
                'verbose_name_plural': 'TiposTemposResidenciasCidadesPopulacoesRuass',
                'db_table': 'tipos_tempos_residencias_cidades_populacoes_ruas',
            },
        ),
        migrations.CreateModel(
            name='TipoTratamentoCaps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoTratamentoCaps',
                'verbose_name_plural': 'TipoTratamentoCapss',
                'db_table': 'tipo_tratamento_caps',
            },
        ),
        migrations.CreateModel(
            name='TipoUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoUnidade',
                'verbose_name_plural': 'TipoUnidades',
                'db_table': 'tipo_unidade',
            },
        ),
        migrations.CreateModel(
            name='TipoUnidadeAtendimentoFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'TipoUnidadeAtendimentoFamilia',
                'verbose_name_plural': 'TipoUnidadeAtendimentoFamilias',
                'db_table': 'tipo_unidade_atendimento_familia',
            },
        ),
        migrations.CreateModel(
            name='VulnerabilidadeSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
            ],
            options={
                'verbose_name': 'VulnerabilidadeSocial',
                'verbose_name_plural': 'VulnerabilidadeSocials',
                'db_table': 'vulnerabilidade_social',
            },
        ),
    ]
