# Generated by Django 5.2.17 on 2026-08-14 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_cbo_ativo_estado_ativo_faixaetaria_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'db_table': 'areas',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Código')),
                ('cnpj', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ')),
                ('razao_social', models.CharField(max_length=255, verbose_name='Razão Social')),
                ('nome_conhecido', models.CharField(max_length=255, verbose_name='Nome Conhecido')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=255, verbose_name='Logradouro')),
                ('logradouro_tipo', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo de Logradouro')),
                ('logradouro_numero', models.CharField(max_length=20, verbose_name='Número')),
                ('logradouro_complemento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento')),
                ('municipio', models.CharField(blank=True, max_length=150, null=True, verbose_name='Município')),
                ('uf', models.CharField(blank=True, max_length=2, null=True, verbose_name='UF')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('icone_mapa', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ícone do Mapa')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('telefone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 1')),
                ('telefone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone 2')),
                ('imovel_situacao', models.CharField(choices=[('Nenhum', 'Nenhum'), ('Próprio', 'Próprio'), ('Alugado', 'Alugado'), ('Cedido', 'Cedido')], default='Nenhum', max_length=20, verbose_name='Situação do Imóvel')),
                ('imovel_social', models.BooleanField(default=False, verbose_name='Imóvel Social?')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_implantacao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Data de Implantação')),
                ('dias_funcionamento', models.JSONField(blank=True, null=True, verbose_name='Dias de Funcionamento')),
                ('area_geo_atuacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Área Geográfica de Atuação')),
                ('area_geo_polig', models.TextField(blank=True, null=True, verbose_name='Polígono Geográfico')),
                ('recursos_disponiveis', models.CharField(blank=True, max_length=255, null=True, verbose_name='Recursos Disponíveis')),
                ('sigla', models.CharField(max_length=50, verbose_name='Sigla')),
                ('natureza', models.CharField(choices=[('Público', 'Público'), ('Privado', 'Privado')], default='Público', max_length=20, verbose_name='Natureza')),
                ('horario_inicio', models.CharField(blank=True, max_length=5, null=True, verbose_name='Horário de Início')),
                ('horario_fim', models.CharField(blank=True, max_length=5, null=True, verbose_name='Horário de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('area_atuacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='core.area', verbose_name='Área de Atuação')),
                ('tipo_unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unidades', to='core.tipounidade', verbose_name='Tipo de Unidade')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'db_table': 'unidades',
            },
        ),
    ]
