# Generated by Django 5.2.17 on 2026-08-14 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_pessoa_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='PessoaSituacaoRua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo_vive_na_rua', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempo que vive na rua')),
                ('tempo_mora_na_cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tempo que mora na cidade')),
                ('vive_com_familia_rua', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Vive com a família na rua?')),
                ('contato_parente_fora_rua', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Tem contato com parente fora da rua?')),
                ('teve_emprego_carteira_assinada', models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Teve emprego com carteira assinada?')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pessoa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='situacao_rua_detalhes', to='core.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Situação de Rua do Cidadão',
                'verbose_name_plural': 'Situações de Rua dos Cidadãos',
                'db_table': 'pessoas_situacoes_rua',
            },
        ),
    ]
