# Generated by Django 5.2.17 on 2026-08-14 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pessoasituacaorua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoasituacaorua',
            name='tempo_vive_na_rua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipostemposresidenciascidadespopulacoesruas', verbose_name='Tempo que vive na rua'),
        ),
    ]
