# Generated by Django 5.2.17 on 2026-08-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pessoasituacaorua_tempo_vive_na_rua'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulacoesRuasTempoDeRua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Tempo de Rua',
                'verbose_name_plural': 'Tempos de Rua',
                'db_table': 'populacoes_ruas_tempo_de_rua',
            },
        ),
        migrations.AlterField(
            model_name='pessoasituacaorua',
            name='contato_parente_fora_rua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tiposcontatosparentes', verbose_name='Contato com parente fora de rua'),
        ),
        migrations.AlterField(
            model_name='pessoasituacaorua',
            name='tempo_mora_na_cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipostemposresidenciascidadespopulacoesruas', verbose_name='Tempo que mora na cidade'),
        ),
        migrations.AlterField(
            model_name='pessoasituacaorua',
            name='tempo_vive_na_rua',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.populacoesruastempoderua', verbose_name='Tempo que vive na rua'),
        ),
    ]
