# Generated by Django 5.2.17 on 2026-08-14 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_populacoesruastempoderua_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='alcoolismo_droga',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Alcoolismo/Drogas?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='ameaca',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Ameaça?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='atendido_centro_pop',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Atendido por Centro POP?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='atendido_cras',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Atendido por CRAS?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='atendido_creas',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Atendido por CREAS?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='atendido_hospital_geral',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Atendido por Hospital Geral?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='atendido_inst_gov',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Atendido por Inst. Gov?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='atendido_inst_nao_gov',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Atendido por Inst. Não Gov?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='atividade_cooperativa',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Atividade em cooperativa?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='atividade_escola',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Atividade em escola?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='atividade_movimento_social',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Atividade em movimento social?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='data_cadastro',
            field=models.DateField(blank=True, null=True, verbose_name='Data Cadastro'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='desemprego',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Desemprego?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='domicilio_particular',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Dorme em domicílio particular?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='dorme_rua',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Dorme na rua?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='egresso',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Egresso?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='exploracao_infantil',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Exploração Infantil?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='exploracao_sexual',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Exploração Sexual?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='historico_pessoal',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico Pessoal'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='nao_atendido',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Não atendido em nenhum local?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='nao_sabe_atividade',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Não sabe se frequentou?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='nao_sabe_motivo',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Não sabe motivos?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='outro_dormir',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Dorme de outra forma?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='outro_motivo',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Outro motivo?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='perda_moradia',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Perda de moradia?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='preferencia',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Preferência?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='problemas_familia',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Problemas familiares?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='profissional_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Profissional Responsável'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='respondeu_atividade',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Respondeu atividades?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='respondeu_motivo',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Respondeu motivos?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='respondeu_sustento',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Respondeu sustento?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='saude',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Tratamento de saúde?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='servico_acolhimento',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Dorme em serviço de acolhimento?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='sustento_carregador',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Sustento como carregador?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='sustento_catador',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Sustento como catador?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='sustento_construcao_civil',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Sustento com cons. civil?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='sustento_guardador_carro',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Sustento como guardador de carro?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='sustento_outro',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Sustento com outro meio?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='sustento_pede_dinheiro',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Sustento pedindo dinheiro?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='sustento_servicos_gerais',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Sustento com servs. gerais?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='sustento_vendas',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Sustento com vendas?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='tempo_domicilio_particular',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frequência semanal dorme em dom. particular'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='tempo_dorme_rua',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frequência semanal dorme na rua'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='tempo_outro_dormir',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frequência semanal dorme de outra forma'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='tempo_servico_acolhimento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Frequência semanal dorme em acolhimento'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='trabalho',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Trabalho?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='transtorno_mental',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Possui transtorno mental?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='usa_alcool',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Usa álcool?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='usa_droga',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Usa drogas?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='violencia_fisica',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Violência Física?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='violencia_psicologica',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Violência Psicológica?'),
        ),
        migrations.AddField(
            model_name='pessoasituacaorua',
            name='violencia_sexual',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Violência Sexual?'),
        ),
        migrations.AlterField(
            model_name='pessoasituacaorua',
            name='teve_emprego_carteira_assinada',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não'), ('Não Sabe', 'Não Sabe')], default='Não', max_length=10, verbose_name='Teve emprego com carteira assinada?'),
        ),
    ]
