# Generated by Django 5.2.17 on 2026-08-14 18:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pessoasituacaorua_alcoolismo_droga_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Simples', 'Simples'), ('Tecnico', 'Técnico')], default='Simples', max_length=10, verbose_name='Tipo de Atendimento')),
                ('data', models.DateField(verbose_name='Data do Atendimento')),
                ('descricao', models.TextField(verbose_name='Descrição/Relato do Atendimento')),
                ('procedimentos_realizados', models.TextField(blank=True, null=True, verbose_name='Procedimentos Realizados')),
                ('providencias_encaminhamentos', models.TextField(blank=True, null=True, verbose_name='Providências e Encaminhamentos')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos', to='core.pessoa', verbose_name='Pessoa Atendida')),
                ('tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Técnico/Responsável')),
                ('tipo_atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tiposatendimentos', verbose_name='Tipo de Atendimento (Tabela Básica)')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos', to='core.unidade', verbose_name='Unidade')),
            ],
            options={
                'verbose_name': 'Atendimento',
                'verbose_name_plural': 'Atendimentos',
                'db_table': 'atendimentos',
                'permissions': [('visualizar_atendimento_tecnico', 'Pode visualizar atendimentos técnicos detalhados')],
            },
        ),
    ]
