# Generated by Django 5.2.17 on 2026-08-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_atendimento'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atendimento',
            old_name='data',
            new_name='data_atendimento',
        ),
        migrations.RenameField(
            model_name='atendimento',
            old_name='descricao',
            new_name='descricao_atendimento',
        ),
    ]
