# Generated by Django 5.2.17 on 2026-08-14 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_data_atendimento_data_atendimento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atendimento',
            options={'permissions': [('visualizar_atendimento_tecnico', 'Can visualizar atendimentos técnicos detalhados')], 'verbose_name': 'Atendimento', 'verbose_name_plural': 'Atendimentos'},
        ),
    ]
