# Generated by Django 5.2.17 on 2026-08-18 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_atendimento_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tiposatendimentos',
            name='modalidade',
            field=models.CharField(choices=[('Simplificado', 'Simplificado'), ('Tecnico', 'Técnico'), ('Ambos', 'Ambos')], default='Ambos', max_length=15, verbose_name='Modalidade de Filtro'),
        ),
        migrations.CreateModel(
            name='AtendimentoSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_atendimento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Atendimento')),
                ('numero_atendimento', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número do Atendimento Técnico')),
                ('modalidade', models.CharField(choices=[('Simplificado', 'Simplificado'), ('Tecnico', 'Técnico')], default='Simplificado', max_length=15, verbose_name='Modalidade de Atendimento')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Finalizado', 'Finalizado'), ('Encaminhamento Tecnico', 'Encaminhamento Técnico'), ('Encaminhamento Interno', 'Encaminhamento Interno')], default='Aberto', max_length=30, verbose_name='Status do Atendimento')),
                ('prontuario', models.CharField(blank=True, max_length=50, null=True, verbose_name='Código do Prontuário')),
                ('data_atendimento', models.DateField(verbose_name='Data do Atendimento')),
                ('data_anotacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Anotação no Sistema')),
                ('funcao_tecnico_responsavel_inicial', models.CharField(blank=True, max_length=150, null=True, verbose_name='Função do Técnico Responsável Inicial')),
                ('descricao_sumaria_atendimento', models.TextField(verbose_name='Descrição Sumária / Observações do Atendimento Inicial')),
                ('funcao_tecnico_responsavel_tecnico', models.CharField(blank=True, max_length=150, null=True, verbose_name='Função do Técnico Responsável Técnico')),
                ('descricao_atendimento_tecnico', models.TextField(blank=True, null=True, verbose_name='Descrição do Atendimento Técnico')),
                ('informacoes', models.TextField(blank=True, null=True, verbose_name='Informações Adicionais')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações Gerais')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_sociais', to='core.familiadomicilio', verbose_name='Família')),
                ('motivo_atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_por_motivo', to='core.tiposatendimentos', verbose_name='Forma de Acesso/Motivo do Atendimento')),
                ('origem_atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_derivados', to='core.atendimentosocial', verbose_name='Origem do Atendimento')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atendimentos_sociais', to='core.pessoa', verbose_name='Pessoa Atendida')),
                ('tecnico_responsavel_inicial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_iniciais_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável Inicial')),
                ('tecnico_responsavel_tecnico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_tecnicos_responsavel', to=settings.AUTH_USER_MODEL, verbose_name='Técnico Responsável do Atendimento Técnico')),
                ('tipo_atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_por_tipo', to='core.tiposatendimentos', verbose_name='Tipo do Atendimento')),
                ('unidade_atendimento_social', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_sociais', to='core.unidade', verbose_name='Unidade de Atendimento')),
            ],
            options={
                'verbose_name': 'Atendimento Social',
                'verbose_name_plural': 'Atendimentos Sociais',
                'db_table': 'atendimentos_sociais',
                'permissions': [('visualizar_atendimento_tecnico', 'Can visualizar atendimentos técnicos detalhados')],
            },
        ),
        migrations.DeleteModel(
            name='Atendimento',
        ),
    ]
