# Generated by Django 5.2.17 on 2026-08-18 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_tiposatendimentos_modalidade_atendimentosocial_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MotivoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'MotivoAtendimento',
                'verbose_name_plural': 'MotivosAtendimentos',
                'db_table': 'motivo_atendimento',
            },
        ),
        migrations.AlterField(
            model_name='atendimentosocial',
            name='motivo_atendimento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atendimentos_por_motivo', to='core.motivoatendimento', verbose_name='Forma de Acesso/Motivo do Atendimento'),
        ),
    ]
