# Generated by Django 5.2.17 on 2026-08-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_motivoatendimento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiadomicilio',
            name='tipo_unidade_atendimento_familia',
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='unidade_atendimento_social_familia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familias_atendidas', to='core.unidade', verbose_name='Unidade Atendimento da Família'),
        ),
    ]
