# Generated by Django 5.2.17 on 2026-08-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_familiadomicilio_tipo_unidade_atendimento_familia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recursohumano',
            name='orgao',
        ),
        migrations.AddField(
            model_name='recursohumano',
            name='unidades',
            field=models.ManyToManyField(blank=True, related_name='profissionais', to='core.unidade', verbose_name='Unidades'),
        ),
        migrations.AlterField(
            model_name='recursohumano',
            name='responsavel_orgao',
            field=models.BooleanField(default=False, verbose_name='Responsável pela Unidade?'),
        ),
    ]
