# Generated by Django 5.2.17 on 2026-08-18 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_recursohumano_orgao_recursohumano_unidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursohumano',
            name='escolaridade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoescolaridade', verbose_name='Escolaridade'),
        ),
    ]
