# Generated by Django 5.2.17 on 2026-08-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_recursohumano_escolaridade'),
    ]

    operations = [
        migrations.AddField(
            model_name='familiadomicilio',
            name='codigo_cadunico',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Código CadÚnico'),
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='data_atualizacao',
            field=models.DateField(auto_now=True, verbose_name='Data da Última Atualização'),
        ),
    ]
