# Generated by Django 5.2.17 on 2026-08-18 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auditorialog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaUnidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transferencia', models.DateTimeField(auto_now_add=True, verbose_name='Data da Transferência')),
                ('justificativa', models.TextField(verbose_name='Justificativa')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias', to='core.familiadomicilio', verbose_name='Família')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('unidade_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_origem', to='core.unidade', verbose_name='Unidade Anterior')),
                ('unidade_nova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='core.unidade', verbose_name='Unidade Nova')),
            ],
            options={
                'verbose_name': 'Transferência de Unidade',
                'verbose_name_plural': 'Transferências de Unidades',
                'db_table': 'transferencias_unidades',
                'ordering': ['-data_transferencia'],
            },
        ),
    ]
