# Generated by Django 5.2.17 on 2026-08-18 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_transferenciaunidade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaPessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transferencia', models.DateTimeField(auto_now_add=True, verbose_name='Data da Transferência')),
                ('motivo', models.CharField(choices=[('Casamento/União', 'Casamento/União'), ('Separação/Divórcio', 'Separação/Divórcio'), ('Independência Financeira', 'Independência Financeira'), ('Mudança de Residência', 'Mudança de Residência'), ('Correção de Cadastro', 'Correção de Cadastro'), ('Outros', 'Outros')], max_length=100, verbose_name='Motivo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('familia_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_saida_membros', to='core.familiadomicilio', verbose_name='Família Anterior')),
                ('familia_nova', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_entrada_membros', to='core.familiadomicilio', verbose_name='Família Nova')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
                ('parentesco_anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferencias_anterior', to='core.tipoparentesco', verbose_name='Parentesco Anterior')),
                ('parentesco_novo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_novo', to='core.tipoparentesco', verbose_name='Parentesco Novo')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_familia', to='core.pessoa', verbose_name='Pessoa')),
            ],
            options={
                'verbose_name': 'Transferência de Pessoa entre Famílias',
                'verbose_name_plural': 'Transferências de Pessoas entre Famílias',
                'db_table': 'transferencias_pessoas',
                'ordering': ['-data_transferencia'],
            },
        ),
    ]
