# Generated by Django 5.2.17 on 2026-08-18 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_transferenciapessoa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logradouro_cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('logradouro_nome', models.CharField(blank=True, max_length=255, null=True, verbose_name='Logradouro')),
                ('logradouro_numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('logradouro_complemento', models.CharField(blank=True, max_length=150, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado (UF)')),
                ('latitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Latitude')),
                ('longitude', models.CharField(blank=True, max_length=50, null=True, verbose_name='Longitude')),
                ('complemento_adicional_endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Complemento Adicional')),
                ('referencia_para_localizacao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ponto de Referência')),
                ('agua_canalizada', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Água Canalizada?')),
                ('possue_banheiro', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Possui Banheiro?')),
                ('calcamento_na_frente_domicilio', models.CharField(blank=True, choices=[('Total', 'Total'), ('Parcial', 'Parcial'), ('Não Existe', 'Não Existe')], max_length=15, null=True, verbose_name='Calçamento em frente?')),
                ('area_dificil_acesso', models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Área de difícil acesso?')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('tipo_abastecimento_agua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoabastecimentoagua', verbose_name='Abastecimento de Água')),
                ('tipo_acessibilidade_domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoacessibilidadedomicilio', verbose_name='Acessibilidade Domicílio')),
                ('tipo_animal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tiposanimais', verbose_name='Animais no Domicílio')),
                ('tipo_coleta_lixo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipocoletalixo', verbose_name='Coleta de Lixo')),
                ('tipo_construcao_domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoconstrucaodomicilio', verbose_name='Tipo de Construção')),
                ('tipo_escoamento_sanitario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoescoamentosanitario', verbose_name='Escoamento Sanitário')),
                ('tipo_especie_domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoespeciedomicilio', verbose_name='Espécie do Domicílio')),
                ('tipo_iluminacao_domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipoiluminacaodomicilio', verbose_name='Tipo de Iluminação')),
                ('tipo_piso_domicilio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tipopisodomicilio', verbose_name='Tipo de Piso')),
                ('tipo_residencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tiporesidencia', verbose_name='Tipo de Residência')),
            ],
            options={
                'verbose_name': 'Domicílio',
                'verbose_name_plural': 'Domicílios',
                'db_table': 'domicilios',
            },
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='familias', to='core.domicilio', verbose_name='Domicílio / Endereço'),
        ),
    ]
