# Generated by Django 5.2.17 on 2026-08-19 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_data_migrate_domicilios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='abuso_de_alcool',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='abuso_de_droga',
        ),
        migrations.RemoveField(
            model_name='pessoasituacaorua',
            name='transtorno_mental',
        ),
        migrations.RemoveField(
            model_name='pessoasituacaorua',
            name='usa_alcool',
        ),
        migrations.RemoveField(
            model_name='pessoasituacaorua',
            name='usa_droga',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='transtorno_mental',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Possui Transtorno Mental?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usa_alcool',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Usa Álcool?'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='usa_droga',
            field=models.CharField(choices=[('Sim', 'Sim'), ('Não', 'Não')], default='Não', max_length=3, verbose_name='Usa Droga?'),
        ),
    ]
