# Generated by Django 5.2.17 on 2026-08-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_pessoa_abuso_de_alcool_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='situacao_de_rua',
            field=models.CharField(choices=[('Padrao', 'Padrão'), ('Rua', 'Situação de Rua'), ('Migrante', 'Migrante'), ('Ambos', 'Situação de Rua e Migrante')], default='Padrao', max_length=15, verbose_name='Situação Atual'),
        ),
    ]
