# Generated by Django 5.2.17 on 2026-08-19 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_pessoa_situacao_de_rua'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True, verbose_name='Chave')),
                ('descricao', models.CharField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
                ('valor', models.CharField(blank=True, max_length=100, null=True, verbose_name='Valor')),
                ('validacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Validação')),
            ],
            options={
                'verbose_name': 'Configuração do Sistema',
                'verbose_name_plural': 'Configurações do Sistema',
                'db_table': 'configuracoes',
            },
        ),
    ]
