# Generated by Django 5.2.17 on 2026-08-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familiadomicilio',
            name='codigo_conta_energia_eletrica',
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='info_acao_jovem',
            field=models.BooleanField(default=False, verbose_name='Recebe Ação Jovem'),
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='info_bolsa_familia',
            field=models.BooleanField(default=False, verbose_name='Beneficiário Bolsa Família'),
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='info_bpc',
            field=models.BooleanField(default=False, verbose_name='Membros Beneficiários BPC'),
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='info_extrema_pobreza',
            field=models.BooleanField(default=False, verbose_name='Situação Extrema Pobreza'),
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='info_insuficiencia_alimentar',
            field=models.BooleanField(default=False, verbose_name='Insuficiência Alimentar na Família'),
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='info_renda_cidada',
            field=models.BooleanField(default=False, verbose_name='Recebe Renda Cidadã'),
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='info_trabalho_infantil',
            field=models.BooleanField(default=False, verbose_name='Indicação de Trabalho Infantil'),
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='possue_meio_transporte',
            field=models.CharField(blank=True, choices=[('Sim', 'Sim'), ('Não', 'Não')], max_length=3, null=True, verbose_name='Possui meio de transporte?'),
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='transporte_automovel',
            field=models.BooleanField(default=False, verbose_name='Transporte Automóvel'),
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='transporte_bicicleta',
            field=models.BooleanField(default=False, verbose_name='Transporte Bicicleta'),
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='transporte_moto',
            field=models.BooleanField(default=False, verbose_name='Transporte Moto'),
        ),
        migrations.AddField(
            model_name='familiadomicilio',
            name='transporte_outros',
            field=models.BooleanField(default=False, verbose_name='Transporte Outros'),
        ),
    ]
