# Generated by Django 5.2.17 on 2026-08-20 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_familiadomicilio_codigo_conta_energia_eletrica_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_beneficio', models.DateField(verbose_name='Data do Benefício')),
                ('observacao', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('valor_beneficio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor do Benefício')),
                ('prontuario_id', models.IntegerField(blank=True, null=True, verbose_name='ID do Prontuário')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Entregue', 'Entregue'), ('Cancelado', 'Cancelado')], default='Pendente', max_length=20, verbose_name='Status')),
                ('profissional_funcao', models.CharField(blank=True, max_length=150, null=True, verbose_name='Função do Profissional')),
                ('data_inatividade', models.DateField(blank=True, null=True, verbose_name='Data de Inatividade')),
                ('motivo', models.TextField(blank=True, null=True, verbose_name='Motivo Inatividade')),
                ('data_entrega', models.DateField(blank=True, null=True, verbose_name='Data da Entrega')),
                ('data_alteracao', models.DateTimeField(auto_now=True, verbose_name='Última Alteração')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficios', to='core.familiadomicilio', verbose_name='Família Beneficiária')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios', to='core.pessoa', verbose_name='Pessoa Beneficiária')),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_cadastrados', to=settings.AUTH_USER_MODEL, verbose_name='Profissional Responsável')),
                ('tecnico_entrega', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_entregues', to=settings.AUTH_USER_MODEL, verbose_name='Técnico da Entrega')),
                ('tipo_beneficio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipobeneficio', verbose_name='Tipo de Benefício')),
                ('unidade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficios_concedidos', to='core.unidade', verbose_name='Unidade Concessora')),
            ],
            options={
                'verbose_name': 'Benefício',
                'verbose_name_plural': 'Benefícios',
                'db_table': 'beneficios',
            },
        ),
    ]
