# Generated by Django 5.2.14 on 2026-08-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_beneficio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentosocial',
            name='modalidade',
            field=models.CharField(choices=[('Simplificado', 'Simplificado'), ('Tecnico', 'Técnico'), ('Encaminhamento Interno', 'Encaminhamento Interno'), ('Referencia', 'Referência'), ('ContraReferencia', 'Contra-Referência')], default='Simplificado', max_length=30, verbose_name='Modalidade de Atendimento'),
        ),
    ]
