# Generated by Django 5.2.17 on 2026-08-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_remove_atendimentosocial_numero_atendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimentosocial',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Finalizado', 'Finalizado'), ('Encaminhado', 'Encaminhado'), ('Encaminhamento Tecnico', 'Encaminhamento Técnico'), ('Encaminhamento Interno', 'Encaminhamento Interno')], default='Aberto', max_length=30, verbose_name='Status do Atendimento'),
        ),
    ]
