# Generated by Django 5.2.17 on 2026-08-21 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_status_esperando_abertura_encaminhamento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAnexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('tipo_mime', models.CharField(blank=True, max_length=150)),
                ('tamanho', models.PositiveBigIntegerField()),
                ('hash_sha256', models.CharField(db_index=True, max_length=64)),
                ('categoria', models.CharField(choices=[('Documento pessoal', 'Documento pessoal'), ('Relatório', 'Relatório'), ('Comprovante', 'Comprovante'), ('Termo', 'Termo'), ('Imagem', 'Imagem'), ('Outro', 'Outro')], default='Outro', max_length=30)),
                ('descricao', models.TextField(blank=True)),
                ('data_documento', models.DateField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexos', to='core.atendimentosocial')),
                ('enviado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL)),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexos', to='core.familiadomicilio')),
                ('pessoa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_anexos', to='core.pessoa')),
            ],
            options={
                'db_table': 'documentos_anexos',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['atendimento', 'ativo'], name='documentos__atendim_f5b8cf_idx'), models.Index(fields=['pessoa', 'ativo'], name='documentos__pessoa__acaf68_idx'), models.Index(fields=['familia', 'ativo'], name='documentos__familia_2eb467_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('atendimento__isnull', False), ('pessoa__isnull', True), ('familia__isnull', True)), models.Q(('atendimento__isnull', True), ('pessoa__isnull', False), ('familia__isnull', True)), models.Q(('atendimento__isnull', True), ('pessoa__isnull', True), ('familia__isnull', False)), _connector='OR'), name='documento_anexo_um_vinculo')],
            },
        ),
    ]
